version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/socketChat
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-key-development-only
      # Mock OAuth credentials for development
      - GITHUB_ID=mock-github-id
      - GITHUB_SECRET=mock-github-secret
      - GOOGLE_CLIENT_ID=mock-google-id
      - GOOGLE_CLIENT_SECRET=mock-google-secret
      # Mock OpenAI key for development
      - OPENAI_API_KEY=mock-openai-key
    volumes:
      - ./:/app
      - /app/node_modules

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socketChat
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
